//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspCoreCardGameEngine.Api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspCoreCardGameEngine.Api.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one card must be specified to play to deck.
        /// </summary>
        public static string At_least_one_card_must_be_specified_to_play_to_deck {
            get {
                return ResourceManager.GetString("At_least_one_card_must_be_specified_to_play_to_deck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot play cards with different values.
        /// </summary>
        public static string Cannot_play_cards_with_different_values {
            get {
                return ResourceManager.GetString("Cannot_play_cards_with_different_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card {0} is not higher or equal to card {1}.
        /// </summary>
        public static string Card__0__is_not_higher_or_equal_to_card__1_ {
            get {
                return ResourceManager.GetString("Card__0__is_not_higher_or_equal_to_card__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card {0} is not lower or equal to the reverse card {1}.
        /// </summary>
        public static string Card__0__is_not_lower_or_equal_to_the_reverse_card__1_ {
            get {
                return ResourceManager.GetString("Card__0__is_not_lower_or_equal_to_the_reverse_card__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards (with ids {0}) cannot be played because they are not in the first non-empty pile {1} of player {2}.
        /// </summary>
        public static string Cards__with_ids__0___cannot_be_played_because_they_are_not_in_the_first_non_empty_pile__1__of_player__2_ {
            get {
                return ResourceManager.GetString("Cards__with_ids__0___cannot_be_played_because_they_are_not_in_the_first_non_empty" +
                        "_pile__1__of_player__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck is empty, cannot draw card for game {0}.
        /// </summary>
        public static string Deck_is_empty__cannot_draw_card_for_game__0_ {
            get {
                return ResourceManager.GetString("Deck_is_empty__cannot_draw_card_for_game__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is another player&apos;s turn, not player {0}.
        /// </summary>
        public static string It_is_another_player_s_turn__not_player__0_ {
            get {
                return ResourceManager.GetString("It_is_another_player_s_turn__not_player__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown game mode {0}.
        /// </summary>
        public static string Unknown_game_mode__0_ {
            get {
                return ResourceManager.GetString("Unknown_game_mode__0_", resourceCulture);
            }
        }
    }
}
